services:
  ws-gateway:
    build: .
    image: ws-gateway:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:3101:3001"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3001/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks: [wsnet]

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
    # لا تعرّض 6379 خارجيًا في الإنتاج
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks: [wsnet]

networks:
  wsnet:
    driver: bridge
